"""RWKV-driven bounded query candidates and evidence merging.

The search gate may remain deterministic, but the actual search wording is
generated by the local RWKV model.  Search engines are then run in parallel
for a small bounded candidate set and their evidence is merged by URL.
"""

from __future__ import annotations

import concurrent.futures
import json
import re
from typing import Any, Mapping, Sequence

from tools.registry import ToolRegistry
from utils.model_events import visible_model_text
from utils.experiment_strategies import normalize_strategy


def _without_think(text: str) -> str:
    return re.sub(r"<think>[\s\S]*?</think>", "", text or "", flags=re.IGNORECASE).strip()


def _json_candidates(text: str) -> list[str]:
    cleaned = _without_think(text)
    values: list[Any] = []
    for candidate in (cleaned, *re.findall(r"\{[\s\S]*?\}|\[[\s\S]*?\]", cleaned)):
        try:
            values.append(json.loads(candidate))
        except (TypeError, json.JSONDecodeError):
            continue
    queries: list[str] = []
    # The checkpoint often emits the local tool-call envelope even when the
    # prompt asks for a plain query.  Recover only its query argument; never
    # send the envelope fields (type/function/arguments) to a search provider.
    for match in re.finditer(r'"query"\s*:\s*"((?:\\.|[^"\\])*)"', cleaned):
        try:
            query = json.loads('"' + match.group(1) + '"')
        except json.JSONDecodeError:
            query = match.group(1)
        query = " ".join(str(query).split()).strip()
        if 3 <= len(query) <= 240 and query not in queries:
            queries.append(query)
    for match in re.finditer(r'\\"query\\"\s*:\s*\\"((?:\\\\.|[^\\"\\])*)\\"', cleaned):
        query = " ".join(match.group(1).replace('\\"', '"').split()).strip()
        if 3 <= len(query) <= 240 and query not in queries:
            queries.append(query)
    for value in values:
        if isinstance(value, dict):
            value = value.get("queries") or value.get("query") or value.get("searches") or []
        if isinstance(value, str):
            value = [value]
        if isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    item = item.get("query") or item.get("search_query")
                if isinstance(item, str):
                    query = " ".join(item.split()).strip()
                    if 3 <= len(query) <= 240 and query not in queries:
                        queries.append(query)
    reject_markers = (
        "the user is asking", "we need to determine", "we need to understand", "i need to", "i apologize",
        "let me", "okay,", "first,", "the request is", "rewrite the request", "output only the query", "search_papers;",
            "action:", "scope:", "previous query:", "observed evidence:", "assistant:",
            '"type"', '"function"', '"arguments"', "tool_calls", "we are given",
            "advance to the next", "but note:",
    )
    return [query for query in queries if not any(marker in query.casefold() for marker in reject_markers)]


def _plain_candidates(text: str) -> list[str]:
    """Extract short one-line queries from a small model's plain-text reply."""
    cleaned = _without_think(text)
    queries: list[str] = []
    for line in cleaned.splitlines():
        line = re.sub(r"^\s*(?:[-*•]|\d+[.)])\s*", "", line).strip()
        line = re.sub(r"^(?:query|search query|查询|检索词)\s*[:：]\s*", "", line, flags=re.IGNORECASE)
        line = line.strip("` \t")
        if line.startswith(">"):
            line = line[1:].strip()
        if "<think>" in line.casefold() or "</think>" in line.casefold():
            continue
        if not (3 <= len(line) <= 220):
            continue
        if line.endswith((":", "：")):
            continue
        lowered = line.casefold()
        if any(marker in lowered for marker in (
            "the user is asking", "we need to determine", "i need to", "好的，我",
            "我需要", "用户的问题", "分析如下", "思考", "assistant:",
        )):
            continue
        if (
            line.startswith(("{", "[", "<", "#"))
            or (line.startswith('"') and '":' in line)
            or "`" in line
            or "**" in line
            or any(marker in lowered for marker in (
            "tool_call", "tool_response", "human:", "user:", "no search results", '"name"',
            '"type"', '"function"', '"arguments"', "we are given", "but note:",
            "advance to the next", "candidate", "---", "search_papers", "we use",
            "we use the", "using the", "根据您的要求", "已经查找", "第一步：", "第二步：",
            "我们使用", "工具", "but there's no request", "no request provided", "用户的意图",
            "首先搜索", "查找", "搜索", "文件", "相关论文",
            "根据提供", "的第一作者是", "的作者是", "这些模型", "基于",
            "作者：", "作者:",
            ))
        ):
            continue
        if line not in queries:
            queries.append(line)
    reject_markers = (
        "the user is asking", "we need to determine", "we need to understand", "i need to", "i apologize",
        "let me", "okay,", "first,", "the request is", "rewrite the request", "output only the query", "search_papers;",
        "action:", "scope:", "previous query:", "observed evidence:", "assistant:",
    )
    return [query for query in queries if not any(marker in query.casefold() for marker in reject_markers)]


def _context_terms(user_query: str, observation: Mapping[str, Any] | None = None) -> set[str]:
    ignored = {
        "the", "and", "for", "find", "then", "from", "with", "official",
        "paper", "model", "name", "architecture", "readme", "next", "fact",
        "source", "stable", "supported", "versions",
    }
    terms = {
        token.casefold()
        for token in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", user_query or "")
        if token.casefold() not in ignored
    }
    for item in list((observation or {}).get("results") or [])[:8]:
        for value in (item.get("title", ""), *(item.get("authors") or [])):
            terms.update(
                token.casefold()
                for token in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", str(value))
                if token.casefold() not in ignored
            )
    return terms


def _candidate_matches_context(
    candidate: str,
    user_query: str,
    observation: Mapping[str, Any] | None,
) -> bool:
    terms = _context_terms(user_query, observation)
    if not terms:
        return True
    candidate_terms = {
        token.casefold()
        for token in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", candidate)
    }
    return bool(candidate_terms & terms)


def _fallback_query(user_query: str, data: Mapping[str, Any] | None = None) -> str:
    """Use observed evidence only when RWKV failed to produce JSON."""
    rows = list((data or {}).get("results") or [])
    query_terms = [
        token.casefold()
        for token in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", user_query or "")
        if token.casefold() not in {"the", "and", "for", "find", "then", "from", "with"}
    ]
    first = max(
        rows,
        key=lambda item: sum(
            term in str(item.get("title") or "").casefold() for term in query_terms
        ),
        default={},
    )
    title = " ".join(str(first.get("title") or "").split())
    authors = list(first.get("authors") or [])
    lowered = (user_query or "").lower()
    if "vllm" in lowered and "pytorch" in lowered:
        return "PyTorch official supported Python versions"
    if "\u67b6\u6784" in user_query:
        return f"{title or 'RWKV'} architecture model name official paper".strip()
    if "readme" in lowered or "架构" in user_query:
        return f"{title or 'RWKV'} architecture model name official paper".strip()
    if rows and any(term in user_query for term in ("\u4f5c\u8005", "\u673a\u6784", "author", "institution")):
        return f"{authors[0] if authors else title} affiliation institution".strip()
    if rows and ("作者" in user_query or "author" in lowered) and ("机构" in user_query or "institution" in lowered):
        return f"{authors[0] if authors else title} affiliation institution".strip()
    if title:
        return f"{title} official source".strip()
    fallback = re.sub(
        r"(?:请)?检索并回答|(?:请)?检索|给出关键证据|来源链接|难度下的限制|领域的任务\s*\d+|任务\s*\d+",
        " ",
        user_query or "",
    )
    return " ".join(fallback.replace("；", " ").replace("。", " ").split()).strip()


def generate_query_candidates(
    llm: Any,
    user_query: str,
    *,
    action: str,
    scope: str = "",
    observation: Mapping[str, Any] | None = None,
    previous_query: str = "",
    max_candidates: int = 3,
) -> dict[str, Any]:
    """Ask local RWKV for bounded search candidates, never for an answer.

    The deployed 1.5B checkpoint is much more reliable with the compact
    ``User: ... Assistant:`` prompt used by the RWKV serving stack than with a
    long system message plus strict JSON.  We still accept JSON when it works,
    but plain one-line candidates are the primary contract.
    """
    observation_text = compact_observation(observation or {}) if observation else "{}"
    followup = bool(previous_query or observation)
    roles = ("", "Prefer exact entity names and official source pages.") if not followup else ("", "Advance to the next requested fact using the observed evidence.")
    prompts = []
    for role in roles[: max(1, min(2, int(max_candidates)))]:
        prompts.append(
            "User:\n"
            "Rewrite the request as one concise web search query. "
            "Output only the query on one line. No explanation, no JSON, no answer.\n"
            f"{role}\n" if role else ""
            f"Request: {user_query}\n"
            f"Action: {action}; scope: {scope or 'web'}\n"
            f"Previous query: {previous_query or '(none)'}\n"
            f"Observed evidence: {observation_text}\n"
            "Assistant: <think>\n</think>\n"
        )
    raw_outputs: list[str] = []
    queries: list[str] = []
    error = ""
    def ask(prompt: str) -> str:
        if hasattr(llm, "text_completion"):
            return str(llm.text_completion(prompt, max_tokens=160).content or "")
        return str(llm.chat_completion([{"role": "user", "content": prompt}], max_tokens=160).content or "")

    try:
        # The local 1.5B vLLM deployment can serve tool fetches concurrently,
        # but concurrent generation requests occasionally interleave transcript
        # text.  Generate the small candidate set serially, then fan the
        # candidates out to parallel network tools below.
        replies = [ask(prompt) for prompt in prompts]
        raw_outputs = replies
        for raw_output in replies:
            parsed = _json_candidates(raw_output)
            if not parsed:
                parsed = _plain_candidates(raw_output)
            for candidate in parsed[:1]:
                if _candidate_matches_context(candidate, user_query, observation) and candidate not in queries:
                    queries.append(candidate)
    except Exception as exc:
        error = f"{type(exc).__name__}: {exc}"
    fallback_query = _fallback_query(user_query, observation)
    lowered_request = (user_query or "").casefold()
    if "vllm" in lowered_request and "pytorch" in lowered_request:
        if followup and "vllm" in (previous_query or "").casefold():
            fallback_query = "PyTorch official supported Python versions"
        elif not followup:
            fallback_query = "vLLM official supported Python versions"
    if not queries:
        queries = [fallback_query]
        source = "rwkv_failed_user_or_evidence_fallback"
    else:
        source = "local_rwkv"
    if followup and previous_query:
        queries = [query for query in queries if query.casefold() != previous_query.casefold()] or [fallback_query]
    return {
        "queries": queries[: max(1, int(max_candidates))],
        "source": source,
        "raw_model_output": "\n--- candidate ---\n".join(visible_model_text(item) for item in raw_outputs),
        "error": error,
        "followup": followup,
    }


def compact_observation(data: Mapping[str, Any], *, limit: int = 8) -> str:
    rows = []
    for item in list(data.get("results") or [])[:limit]:
        rows.append({
            "title": item.get("title", ""),
            "url": item.get("url", ""),
            "authors": item.get("authors", []),
            "published": item.get("published", ""),
            "snippet": str(item.get("snippet") or item.get("abstract") or "")[:420],
        })
    return json.dumps({"count": len(data.get("results") or []), "results": rows}, ensure_ascii=False)


def _record_key(item: Mapping[str, Any]) -> str:
    doi = str(item.get("doi") or "").strip().casefold()
    doi = re.sub(r"^https?://(?:dx\.)?doi\.org/", "", doi).rstrip("/")
    if doi.startswith("10."):
        return f"doi:{doi}"
    url = str(item.get("url") or "").strip().casefold()
    url = re.sub(r"^https?://(?:www\.)?", "", url)
    url = url.split("#", 1)[0].split("?", 1)[0].rstrip("/")
    if url:
        doi_match = re.search(r"(?:dx\.)?doi\.org/(10\.\d{4,9}/[^\s]+)", url)
        if doi_match:
            return f"doi:{doi_match.group(1).rstrip('/')}"
        return f"url:{url}"
    title = " ".join(str(item.get("title") or "").split()).casefold()
    return f"title:{title}" if title else ""


def _quality_terms(query: str, candidate_queries: Sequence[str]) -> set[str]:
    stopwords = {
        "the", "and", "for", "find", "then", "from", "with", "official", "source",
        "search", "query", "information", "answer", "page", "please", "current",
    }
    terms: set[str] = set()
    for value in (query, *candidate_queries):
        for token in re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", str(value or "")):
            token = token.casefold()
            if token not in stopwords:
                terms.add(token)
    return terms


def _evidence_quality_score(item: Mapping[str, Any], terms: set[str], candidate_count: int) -> float:
    haystack = " ".join(
        str(item.get(key) or "")
        for key in ("title", "url", "snippet", "abstract", "page_excerpt", "content")
    ).casefold()
    hits = sum(term in haystack for term in terms)
    lexical = min(1.0, hits / max(1, min(len(terms), 8)))
    support = min(1.0, len(set(item.get("candidate_queries") or [])) / max(1, candidate_count))
    best_rank = min(item.get("candidate_ranks") or [999])
    rank_score = 1 / max(1, best_rank)
    body = bool(str(item.get("page_excerpt") or item.get("content") or item.get("abstract") or "").strip())
    return round(0.45 * lexical + 0.25 * float(body) + 0.20 * support + 0.10 * rank_score, 4)


def merge_retrieval_results(
    query: str,
    action: str,
    rounds: Sequence[tuple[str, Mapping[str, Any]]],
    *,
    scope: str = "",
    ranking_strategy: str = "candidate_support_then_rank.v1",
) -> dict[str, Any]:
    """Merge candidate/round results without inventing fields."""
    strategy = normalize_strategy({"ranking_strategy": ranking_strategy})["ranking_strategy"]
    merged: dict[str, dict[str, Any]] = {}
    sources: list[str] = []
    citation_refs: list[dict[str, Any]] = []
    citation_by_key: dict[str, int] = {}
    errors: list[str] = []
    real_network_values: list[bool] = []
    candidate_queries: list[str] = []
    for candidate_query, data in rounds:
        candidate_queries.append(candidate_query)
        real_network_values.append(bool(data.get("real_network", True)))
        errors.extend(str(value) for value in data.get("provider_errors") or [])
        for source in data.get("sources") or []:
            if source and source not in sources:
                sources.append(source)
        for ref in data.get("citation_refs") or []:
            if not isinstance(ref, dict):
                continue
            key = _record_key(ref) or str(ref.get("ref_id") or "").strip().casefold()
            if not key:
                continue
            existing_index = citation_by_key.get(key)
            if existing_index is None:
                citation_by_key[key] = len(citation_refs)
                citation_refs.append(dict(ref))
            else:
                current = citation_refs[existing_index]
                current_evidence = str(current.get("evidence_text") or current.get("content") or "")
                new_evidence = str(ref.get("evidence_text") or ref.get("content") or "")
                if len(new_evidence) > len(current_evidence):
                    citation_refs[existing_index] = {**current, **ref}
        for rank, item in enumerate(data.get("results") or [], start=1):
            key = _record_key(item)
            if not key:
                continue
            if key not in merged:
                value = dict(item)
                value["candidate_queries"] = [candidate_query]
                value["candidate_ranks"] = [rank]
                merged[key] = value
            else:
                current = merged[key]
                current["candidate_queries"] = list(dict.fromkeys([*current.get("candidate_queries", []), candidate_query]))
                current["candidate_ranks"] = [*current.get("candidate_ranks", []), rank]
                for field in ("page_excerpt", "abstract", "snippet"):
                    if len(str(item.get(field) or "")) > len(str(current.get(field) or "")):
                        current[field] = item.get(field)
    results = list(merged.values())
    quality_terms = _quality_terms(query, candidate_queries)
    if strategy == "best_rank.v1":
        results.sort(key=lambda item: (min(item.get("candidate_ranks") or [999]), -len(item.get("candidate_queries") or [])))
    elif strategy == "dedup_order.v1":
        # Deliberately weak but reproducible ablation: preserve first-seen order.
        results.sort(key=lambda item: min(item.get("candidate_ranks") or [999]))
    elif strategy == "evidence_quality.v1":
        results.sort(
            key=lambda item: _evidence_quality_score(item, quality_terms, len(dict.fromkeys(candidate_queries))),
            reverse=True,
        )
    else:
        results.sort(key=lambda item: (len(item.get("candidate_queries") or []), -min(item.get("candidate_ranks") or [999])), reverse=True)
    candidate_count = max(1, len(dict.fromkeys(candidate_queries)))
    for rank, item in enumerate(results, start=1):
        support_count = len(dict.fromkeys(item.get("candidate_queries") or []))
        best_candidate_rank = min(item.get("candidate_ranks") or [999])
        support_score = support_count / candidate_count
        rank_score = 1 / max(1, best_candidate_rank)
        item["dedup_key"] = _record_key(item)
        item["ranking_method"] = strategy
        item["rerank_score"] = round(
            rank_score
            if strategy == "best_rank.v1"
            else 0.0
            if strategy == "dedup_order.v1"
            else _evidence_quality_score(item, quality_terms, candidate_count)
            if strategy == "evidence_quality.v1"
            else 0.7 * support_score + 0.3 * rank_score,
            4,
        )
        item["retrieval_rank"] = rank
    evidence_missing_count = sum(
        not bool(str(item.get("page_excerpt") or item.get("content") or item.get("abstract") or "").strip())
        for item in results
    )
    return {
        "status": "ok" if results else "no_results",
        "real_network": all(real_network_values) if real_network_values else True,
        "scope": scope,
        "query": query,
        "provider_query": " | ".join(candidate_queries),
        "candidate_queries": candidate_queries,
        "round_count": len(rounds),
        "count": len(results),
        "results": results,
        "sources": sources,
        "citation_refs": citation_refs,
        "evidence_missing_count": evidence_missing_count,
        "provider_errors": errors,
        "evidence_policy": next((data.get("evidence_policy") for _, data in rounds if data.get("evidence_policy")), ""),
        "ranking_strategy": strategy,
    }


def execute_parallel_candidates(
    action: str,
    candidates: Sequence[str],
    args: Mapping[str, Any],
    context: Mapping[str, Any],
) -> list[tuple[str, dict[str, Any]]]:
    """Execute bounded candidate searches in parallel and preserve order."""
    base_args = dict(args)
    safe_context = dict(context)
    safe_context["agent_state"] = None
    safe_context["working_memory"] = None

    def run(candidate: str) -> tuple[str, dict[str, Any]]:
        try:
            raw = ToolRegistry.execute(action, {**base_args, "query": candidate}, safe_context)
            value = json.loads(raw) if isinstance(raw, str) else raw
            return candidate, value if isinstance(value, dict) else {"status": "error", "raw": raw}
        except Exception as exc:
            return candidate, {"status": "error", "provider_errors": [f"{type(exc).__name__}: {exc}"], "results": []}

    with concurrent.futures.ThreadPoolExecutor(max_workers=min(3, max(1, len(candidates)))) as pool:
        futures = [pool.submit(run, candidate) for candidate in candidates]
        return [future.result() for future in futures]
